apiVersion: v1
kind: Pod
metadata:
  name: s3-access-test
spec:
  serviceAccountName: s3-reader
  containers:
  - name: awscli
    image: amazonlinux
    command: ["/bin/sh"]
    args: ["-c", "yum install -y aws-cli && aws s3 ls s3://config-bucket-285305988025"]
